### ISSUE TITLE
Changes Saves for Edit Color

### ISSUE THREAD

**Issue by RevONiKO** [pozzum/WrestleMINUS#5]
We can't saves the changes and choose the color in Color edit with WrestleMinus .
![2019-03-11_184201](https://user-images.githubusercontent.com/48451486/54145441-55ca0c80-442e-11e9-8877-657e751a0a3b.png)

And same thing for Show Edit
![2019-03-12_204908](https://user-images.githubusercontent.com/48451486/54231224-69e23c80-4508-11e9-816c-72487be586aa.png)

**Comment by pozzum** [comment]
https://cdn.discordapp.com/attachments/283102473940369409/560597530077822979/unknown.png

Apologies for the delay.  Save changes should show once you have made a change to the light or to the show edit and then hit enter.

**Comment by pozzum** [comment]
I will eventually have it there but greyed out until edited in future versions.
