### ISSUE TITLE
Error saving to nibj files

### ISSUE THREAD

**Issue by 12pearcj** [pozzum/WrestleMINUS#7]
Trying to save to a nibj file causes this error:
![image](https://user-images.githubusercontent.com/11364060/61580707-b5d36c80-ab0c-11e9-860c-f06bf1267089.png)

I haven't tested with other nibj files, so it might be a file path issue, 

EDIT: Forgot to mention that the file in question is in pac\misc\parameter\todo. The filename is "todo_wwe19_champion_belt_too_dark_cutscene_no.pac"

**Comment by pozzum** [comment]
so I cannot seem to recreate this now along with some other fixes.  This issue should be resolved to the best of my knowledge but I am still progressing on it.
